import { CapabilityItem, ProcessStep, EventCategory, ServiceLevel, FAQItem } from './types';

export const CAPABILITIES: CapabilityItem[] = [
  {
    id: 'multi-camera',
    title: 'MULTI-CAMERA PRODUCTION',
    shortDesc: 'Professional multi-camera coverage designed to capture the event from multiple perspectives.',
    fullDesc: 'From 2-camera talk setups to 8+ camera live concert rigs, our multi-camera systems utilize Sony FX6 / FX3 and Blackmagic URSA Broadcast 4K cameras with motorized PTZ robotics, wireless video transmitters, and cinema lenses to capture every nuance of your live event.',
    specs: ['4K / 1080p60 Uncompressed Capture', 'NDI & 12G-SDI Signal Infrastructure', 'Wireless Teradek Zero-Delay Transmission', 'Symphonic Zoom & Prime Lenses'],
    equipment: ['Sony Cinema Line Cameras', 'Blackmagic Broadcast Systems', 'Canon Broadcast Lenses', 'DJI Ronin Stabilizers'],
    icon: 'Video',
    image: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'live-switching',
    title: 'LIVE SWITCHING',
    shortDesc: 'Real-time vision mixing and camera direction for dynamic broadcast-quality coverage.',
    fullDesc: 'Our technical directors execute seamless vision mixing on Blackmagic ATEM Constellation and Ross Video switchers. We deliver instant instant-replay, live multi-view monitoring, chroma keying, and multi-destination program feeds tailored for both online viewers and venue LED displays.',
    specs: ['20-Input 4K ATEM Constellation Mixers', 'Ultra-low Latency Hardware Switching', 'Hardware Instant Replay Systems', 'ISO Recording Per Input'],
    equipment: ['Blackmagic ATEM 4 M/E Constellation', 'vMix Pro 4K Systems', 'Elgato Stream Deck XL Arrays', 'Multi-Viewer Field Monitors'],
    icon: 'Sliders',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'broadcast-audio',
    title: 'BROADCAST AUDIO',
    shortDesc: 'Professional audio integration designed to deliver clear, balanced sound to the online audience.',
    fullDesc: 'Concert and conference audio online often suffers from poor mixing. We deploy Dante digital audio networks, Behringer X32 / Allen & Heath SQ consoles, automixing for keynote speakers, and mastering compressors to ensure speech and musical performances sound album-ready.',
    specs: ['Dante & MADI Digital Audio Protocols', 'EBU R128 Loudness Compliance (-14 LUFS)', 'Automixed Keynote Wireless Mics', 'Multitrack Raw Audio Recording'],
    equipment: ['Allen & Heath SQ-6 Digital Mixers', 'Shure Axient Digital Wireless Systems', 'Neumann & Sennheiser Microphones', 'Waves Live Audio Processing'],
    icon: 'Volume2',
    image: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'graphics-overlays',
    title: 'GRAPHICS & OVERLAYS',
    shortDesc: 'Branded titles, lower thirds, transitions and live visual systems.',
    fullDesc: 'Elevate your stream with broadcast-grade graphics. We create custom animated lower thirds, speaker title cards, live lower-third scoreboards, real-time audience polling, QR code overlays, and sponsor placement cards synced with your event branding.',
    specs: ['Alpha Channel Transparent Video Motion', 'Dynamic Data-Driven Speaker Labels', 'Real-Time Audience Polling Overlays', 'Custom Stinger Transitions'],
    equipment: ['vMix Graphic Engines', 'Singular.live Cloud Graphics', 'Adobe After Effects Render Rigs', 'Custom HTML5 Data Overlays'],
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'multi-platform',
    title: 'MULTI-PLATFORM STREAMING',
    shortDesc: 'Stream simultaneously to YouTube, Facebook, Instagram, Twitch or custom RTMP destinations.',
    fullDesc: 'Reach your audience wherever they gather. Using hardware bonded cellular transceivers (LiveU / Peplink) and redundant cloud distribution servers, we push pristine 1080p or 4K streams concurrently to YouTube, LinkedIn, X, Facebook, and custom private portals.',
    specs: ['Bonded 5G / Starlink Satellite Connectivity', 'SRT & Custom Secure RTMP / RTMPS', 'Concurrent 10+ Destination Distribution', 'Failover Redundant Signal Paths'],
    equipment: ['LiveU Live Streaming Encoders', 'Peplink SpeedFusion SD-WAN', 'Resi High-Reliability Encoders', 'Teradek Prism Flex 4K'],
    icon: 'Globe',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'onsite-production',
    title: 'ON-SITE PRODUCTION',
    shortDesc: 'Technical direction and experienced production crew managing the live workflow.',
    fullDesc: 'We supply complete, seasoned crews — including Technical Directors, Vision Mixers, Camera Operators, Audio Engineers, Graphics Operators, and Floor Managers. Our crew handles load-in, rig testing, comms setup, live execution, and load-out smoothly.',
    specs: ['Dedicated Technical Director & Crew', 'Clear-Com Wireless Intercom Matrix', 'Full Redundancy Power & UPS Backups', 'Comprehensive Site Safety Protocol'],
    equipment: ['Hollyland Mars T1000 Intercoms', 'APC Smart-UPS Pro Backup Power', 'Modular Flightcase Racks', 'Broadcast Monitoring Station'],
    icon: 'Users',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'led-hybrid',
    title: 'LED & HYBRID PRODUCTION',
    shortDesc: 'Integration with LED environments, presentations and hybrid event systems.',
    fullDesc: 'Synchronize on-site LED walls, stage monitors, and remote Zoom/Teams presenters with the broadcast stream. We manage low-latency return video feeds, remote speaker green rooms, and venue presentation switching so both physical and virtual attendees share the same experience.',
    specs: ['LED Video Wall Signal Mapping', 'Low-Latency Speaker Return Video', 'Bidirectional Zoom / Teams Integration', 'Presenter Prompting & Countdown Clocks'],
    equipment: ['Novastar LED Processors', 'Barco Master Video Switchers', 'Broadcast Teleprompter Kits', 'Low-latency SRT Return Monitors'],
    icon: 'Monitor',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
  },
  {
    id: 'recording-archive',
    title: 'RECORDING & ARCHIVE',
    shortDesc: 'Reliable local recording and archival so the production can continue beyond the livestream.',
    fullDesc: 'Never lose a second of your event. We record isolated (ISO) feeds for every camera plus master program feeds in Apple ProRes 422 / DNxHR to NVMe RAID storage, delivering instant post-event media archives and highlight reels ready for editing.',
    specs: ['Isolated ISO Camera Feeds + Program Master', 'Apple ProRes 422 / H.265 High Bitrate', 'Dual-NVMe RAID Redundant Backup', 'Immediate Same-Day File Handoff'],
    equipment: ['Blackmagic HyperDeck Studio 4K', 'Atomos Sumo 19" HDR Recorders', 'SanDisk Professional RAID Drives', 'High-speed Cloud Ingestion Server'],
    icon: 'Database',
    image: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?q=80&w=1200&auto=format&fit=crop',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    number: '01',
    title: 'UNDERSTAND',
    description: 'We understand your event, audience, venue, schedule and production requirements.',
    keyActivity: 'Comprehensive briefing & venue technical assessment',
    deliverables: ['Production Brief', 'Venue Site Survey', 'Signal Path Audit', 'Audience Reach Map'],
  },
  {
    number: '02',
    title: 'PLAN',
    description: 'We design the production workflow, camera configuration, streaming architecture and technical requirements.',
    keyActivity: 'System architecture, floor plans, and run-of-show scheduling',
    deliverables: ['Camera Placement Diagram', 'Bandwidth & Network Plan', 'Graphics Asset Template', 'Run of Show Schedule'],
  },
  {
    number: '03',
    title: 'PRODUCE',
    description: 'Our crew manages the live production, switching, audio, graphics and broadcast workflow.',
    keyActivity: 'On-site rig setup, rehearsal, and flawless live execution',
    deliverables: ['Live Multi-Cam Switching', 'Broadcast Audio Mixing', 'Real-Time Graphics Injection', 'Multi-Viewer Monitoring'],
  },
  {
    number: '04',
    title: 'DELIVER',
    description: 'Your broadcast reaches audiences across the platforms that matter.',
    keyActivity: 'Redundant multi-destination streaming with zero dropouts',
    deliverables: ['Simulcast Platform Streams', 'Private Client Video Portal', 'Live Stream Telemetry Log', 'Viewer Engagement Analytics'],
  },
  {
    number: '05',
    title: 'ARCHIVE',
    description: 'Where required, the production is recorded and preserved for future use.',
    keyActivity: 'Master ProRes archiving & instant media handoff',
    deliverables: ['High-Bitrate Program Master', 'Individual ISO Camera Footage', 'Multitrack Audio Files', 'Cloud Archival Access'],
  },
];

export const EVENT_CATEGORIES: EventCategory[] = [
  {
    id: 'conferences',
    title: 'CONFERENCES & SUMMITS',
    description: 'Multi-stage keynote capture, presentation graphics, remote Q&A, and high-definition hybrid attendee streaming for global corporate assemblies.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '3-6 Cameras (Wide, Keynote Tight, Audience, Stage Tracking)',
    keyRequirements: ['Automixed Wireless Mics', 'Presenter Slide Capture', 'Low-latency SRT Return'],
  },
  {
    id: 'concerts',
    title: 'CONCERTS & FESTIVALS',
    description: 'High-energy musical performances captured with dynamic camera movement, pristine multitrack audio mixing, and immersive stage lighting integration.',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '4-8 Cameras (FOH Wide, Jib Crane, Pit Handhelds, Stage Robotic PTZ)',
    keyRequirements: ['Dante Concert Audio Feed', 'Stage Stinger Graphics', '4K ISO Camera Recording'],
  },
  {
    id: 'churches',
    title: 'CHURCHES & MINISTRIES',
    description: 'Reverent, immersive live worship broadcasts connecting global congregations with crystal-clear acoustics, lower-third scripture lyrics, and reliable weekly scheduling.',
    image: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '2-4 Cameras (Altar Wide, Pastor Medium, Choir/Musician Angles)',
    keyRequirements: ['Scripture & Lyric Overlays', 'Multicast to YouTube/FB', 'Archival Sunday Recordings'],
  },
  {
    id: 'corporate',
    title: 'CORPORATE EVENTS',
    description: 'Town halls, annual general meetings, and internal executive announcements streamed securely with end-to-end encryption and viewer access control.',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '2-4 Cameras (Executive Desk, Podium, Audience Q&A)',
    keyRequirements: ['Encrypted Custom RTMP', 'Branded Lower Thirds', 'PowerPoint / Keynote PIP'],
  },
  {
    id: 'brand-activations',
    title: 'BRAND ACTIVATIONS',
    description: 'Pop-up experiences, immersive experiential launches, and influencer showcases engineered for massive online engagement and viral social reach.',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '2-4 Mobile & PTZ Rigs',
    keyRequirements: ['Vertical 9:16 Social Streams', 'Live Interactive Polling', 'Custom Sponsor Overlays'],
  },
  {
    id: 'weddings',
    title: 'WEDDINGS & PRIVATE EVENTS',
    description: 'Discreet, high-elegance multi-camera coverage for overseas family and loved ones who cannot attend in person.',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '2-3 Cinema Line Cameras (Unobtrusive Rigs)',
    keyRequirements: ['Private Password Protected Feed', 'Broadcast Audio Mic Kits', 'Immediate Archive Copy'],
  },
  {
    id: 'sports',
    title: 'SPORTS & TOURNAMENTS',
    description: 'Fast-paced athletic coverage featuring instant replays, live scoreboard integration, multi-angle camera positions, and play-by-play audio feeds.',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '4-8 Cameras (High Center, Tight Action, Endzone, Slow-Mo ISO)',
    keyRequirements: ['Hardware Slow-Motion Replay', 'Real-time Scorebug Overlays', 'Commentator Headsets'],
  },
  {
    id: 'product-launches',
    title: 'PRODUCT LAUNCHES',
    description: 'High-impact reveal broadcasts with cinematic lighting, crisp macro camera angles, and global press access across multiple digital destinations.',
    image: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '3-5 Cameras (Wide Stage, Product Close-up Macro, Audience Reaction)',
    keyRequirements: ['Ultra-HD 4K Streaming', 'Simultaneous Multi-Platform Push', 'Sub-second Latency'],
  },
  {
    id: 'graduations',
    title: 'GRADUATIONS',
    description: 'Academic ceremonies captured with individual graduate name lower thirds, dual stage cameras, and live streams accessible worldwide.',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '3-4 Cameras (Processional Wide, Stage Procession, Audience)',
    keyRequirements: ['Automated Name Graphics Sync', 'High Capacity Web CDN', 'On-Demand Replay Archive'],
  },
  {
    id: 'charity',
    title: 'CHARITY & FUNDRAISING',
    description: 'Gala broadcasts featuring live donation total tickers, emotional testimonial videos, and real-time donor recognition displays.',
    image: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '2-4 Cameras',
    keyRequirements: ['Live Donation Meter Overlay', 'Auction Mic Audio Integration', 'Redundant Bonding'],
  },
  {
    id: 'virtual-hybrid',
    title: 'VIRTUAL & HYBRID EVENTS',
    description: 'Seamless bridging between on-stage presenters and remote international speakers with zero-latency video return feeds and interactive workshops.',
    image: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=1200&auto=format&fit=crop',
    cameraSetup: '3-5 Cameras + Remote Caller Ingest Rigs',
    keyRequirements: ['Bi-directional Audio/Video Return', 'LED Wall Background Mapping', 'Dedicated Remote Stage Director'],
  },
];

export const SERVICE_LEVELS: ServiceLevel[] = [
  {
    id: 'starter',
    name: 'STARTER',
    suitableFor: 'Intimate gatherings, press briefings, single-speaker keynotes, and small workshops.',
    cameraCount: '1–2 CAMERAS',
    features: [
      '1–2 Cinema Line 4K Cameras',
      'Basic Broadcast Audio Integration',
      'Single Streaming Platform (YouTube / FB / RTMP)',
      'High-Definition Local Recording',
      'Standard Lower Third Graphics',
      '1 Production Operator',
    ],
    technicalHighlights: ['1080p60 Stream Output', 'Stereo XLR Audio Capture', 'Core Lower Thirds Template', 'Same-Day Digital Master Delivery'],
    recommendedFor: 'Small venues, localized audiences, single-room keynotes',
  },
  {
    id: 'standard',
    name: 'STANDARD',
    badge: 'MOST POPULAR',
    suitableFor: 'Medium-sized conferences, churches, corporate town halls, and panel discussions.',
    cameraCount: '3–4 CAMERAS',
    features: [
      '3–4 Multi-Angle Cameras (Wide, Tight, PTZ)',
      'Dedicated Vision Mixer & Live Switching',
      'Custom Branded Broadcast Graphics & Lower Thirds',
      'Simultaneous Streaming to Up to 2 Platforms',
      'Multitrack Audio Mixing & Wireless Mics',
      'Full Program Recording + ISO Backups',
      '2–3 Experienced Production Crew',
    ],
    technicalHighlights: ['4K Ingest / 1080p60 Output', 'Dante Audio Console Integration', 'Live Lower-Third Titles & Slides', 'Bonded Cellular Network Option'],
    recommendedFor: 'Corporate AGMs, regional conferences, Sunday worship, product demos',
  },
  {
    id: 'premium',
    name: 'PREMIUM',
    suitableFor: 'Large conferences, multi-stage summits, concerts, festivals, and major brand events.',
    cameraCount: '4–6 CAMERAS',
    features: [
      '4–6 Professional Cinema/Broadcast Cameras',
      'Full Production Crew (Technical Director, Camera Ops, Audio Tech, Graphics Tech)',
      'Advanced Motion Graphics, Stinger Transitions & Lower Thirds',
      'Simultaneous Multi-Platform Streaming (3+ Destinations)',
      'LED Screen & Venue Stage Monitor Integration',
      'ProRes ISO Recording for Every Camera Feed',
      'Bonded 5G / Satellite Internet Redundancy',
    ],
    technicalHighlights: ['ATEM 4 M/E Constellation Switcher', 'EBU R128 Audio Mastering', 'Live Instant Replay Capability', 'Redundant Hardware Encoders'],
    recommendedFor: 'National summits, live concerts, international product reveals, hybrid galas',
  },
  {
    id: 'global-elite',
    name: 'GLOBAL ELITE',
    suitableFor: 'Major international productions, multi-day global congresses, and broadcast-network level events.',
    cameraCount: 'CUSTOM / 6+ CAMERAS',
    features: [
      'Custom Multi-Camera Rigging (6+ Cameras, Jibs, Wireless Gimbal, PTZ)',
      'Multi-Day International Crew Deployment',
      'Dedicated On-Site Production Manager & Technical Director',
      'Full Broadcast Infrastructure & OB Flypack Racks',
      'Custom RTMP & Encrypted Satellite / SRT Signal Delivery',
      'Bi-Directional Remote Speaker Ingest & Green Room Rigs',
      'Comprehensive On-Site Post-Production & Daily Highlight Edits',
    ],
    technicalHighlights: ['12G-SDI / 4K UHD Workflow', 'Dual-Redundant Power & Network Bonding', 'Multi-Language Audio Track Support', 'Dedicated Satellite Uplink Integration'],
    recommendedFor: 'Global corporate summits, international music festivals, multi-city broadcasts',
  },
];

export const FAQ_ITEMS: FAQItem[] = [
  {
    category: 'General',
    question: 'What types of events do you cover?',
    answer: 'D1 Streams provides live production for conferences, summits, concerts, music festivals, church services, corporate town halls, brand activations, product launches, sports tournaments, weddings, graduations, and hybrid virtual events worldwide.',
  },
  {
    category: 'Logistics',
    question: 'Do you operate outside the UK?',
    answer: 'Yes. While based in the United Kingdom, D1 Streams operates globally. Our modular flightcase production rigs (OB Flypacks) are engineered for rapid international air transport and global crew deployment.',
  },
  {
    category: 'Technical',
    question: 'How many cameras can you provide?',
    answer: 'Our standard configurations range from 1–2 camera setups for intimate events up to 6–8+ camera environments featuring wide stage angles, tight presenter tracking, audience reaction cameras, robotic PTZ systems, and wireless handheld cinema rigs.',
  },
  {
    category: 'Technical',
    question: 'Which platforms can you stream to?',
    answer: 'We stream simultaneously to any major platform including YouTube, Facebook Live, LinkedIn Live, X (Twitter), Twitch, Vimeo, Instagram, or custom private event portals.',
  },
  {
    category: 'Technical',
    question: 'Can you stream to custom RTMP destinations?',
    answer: 'Absoluty. We support secure RTMP, RTMPS, and SRT (Secure Reliable Transport) protocols to push streams directly into client intranets, custom enterprise portals, or proprietary paywall systems.',
  },
  {
    category: 'Logistics',
    question: 'Do you provide on-site production crews?',
    answer: 'Yes. Every D1 Streams deployment includes an experienced, professional technical crew — including Technical Directors, Vision Mixers, Camera Operators, Audio Engineers, and Floor Managers.',
  },
  {
    category: 'Technical',
    question: 'Can you integrate with existing venue audio?',
    answer: 'Yes. We routinely interface directly with venue front-of-house (FOH) sound consoles via XLR, Dante digital audio networks, or MADI, applying broadcast mastering compressors and EQ to deliver pristine audio to online viewers.',
  },
  {
    category: 'Technical',
    question: 'Can you integrate LED screens?',
    answer: 'Yes. We provide video mapping and return feeds for stage LED walls, confidence monitors, and venue IMAG (Image Magnification) displays while maintaining zero noticeable latency.',
  },
  {
    category: 'Technical',
    question: 'Can you provide recording?',
    answer: 'Yes. Every production includes local master program recording as standard. On Standard, Premium, and Global Elite tiers, we also capture individual ISO (Isolated) high-bitrate feeds for every camera in Apple ProRes or H.265.',
  },
  {
    category: 'Booking',
    question: 'How far in advance should we book?',
    answer: 'We recommend booking 3 to 6 weeks in advance for domestic UK events, and 6 to 12 weeks for complex international or multi-camera festival productions. However, we also accommodate short-notice emergency broadcast requests whenever crew schedule allows.',
  },
  {
    category: 'Booking',
    question: 'Can you create a custom production package?',
    answer: 'Yes. Every live event is unique. Our team works closely with your event producers to design a custom technical specification tailored to your venue acoustics, lighting, camera requirements, and budget.',
  },
];
